version: "3"
services:
  parking-db:
    image: "mysql:8.0.32"
    container_name: parking-db
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "parkingdb"
      MYSQL_USER: "parking"
      MYSQL_PASSWORD: "parking"

  parking-back-app:
    build: ./parkingbackapp
    container_name: parking-back
    environment:
      - DB_SERVER=parking-db
    ports:
      - 8080:8080
    links:
      - parking-db

  parking-front-app:
    build: ./parkingfrontapp
    container_name: parking-front-app
    ports:
      - 3000:3000
    links:
      - parking-back-app

volumes:
  db_data:
