version: "3"

services:
  # Setup local instance of the Backend Server
  backend:
    build: ./parkingbackapp
    # Set the network for the two service so that they can communicate with each other
    networks:
      - reactdrf
    volumes:
      - drf-backend:/drf_src
    # Map port 8000 to port 8199 so that we can access the application on
    # our host machine by visiting 127.0.0.1:8199
    ports:
      - "8199:8080"

  # Create a service called web for the React + Redux app
  web:
    # Build an image from the files in the project root directory (Dockerfile)
    build: .
    depends_on:
      - backend
    # Mount the container `/drf` folder to the a `src` folder in the location
    # of the Dockerfile on the host machine.
    volumes:
      - drf-react-react:/usr/src/app/
    restart: always
    # Map port 3000 to port 8081 so that we can access the application on
    # our host machine by visiting 127.0.0.1:8081
    ports:
      - "8081:3000"
    networks:
      - reactdrf
    # bdd: TODO
networks:
  reactdrf:
volumes:
  drf-backend:
  drf-react-react:
